<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Sanh2.aspx.cs" Inherits="WARM.WebForm5" %>
<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" runat="server">
    <script type="text/javascript" src="../../Scripts/jquery.js"></script>
    <script type="text/javascript" src="../../Scripts/jquery-ui.min.js"></script>
    <script type="text/javascript" src="../../Scripts/bootstrap.js"></script>
    <script type="text/javascript" src="../../Scripts/bootstrap.min.js"></script>
    <script type="text/javascript" src="../../Scripts/breadcrumbs.js"></script>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">

<ul id="nav">
	<li><a href="../..">Trang Chủ > </a></li>
	<li><a href="../ChonTang.aspx" class="arrow">Tham Quan > </a>
		<ul>
			<li><a href="#" class="sub">Đăng Ký</a></li>
			<li><a href="#" class="sub">Đặt Bàn</a></li>
			<li><a href="#" class="sub">Đặt Món</a></li>
			<li><a href="#" class="sub">Chi Tiết Món</a></li>
			<li><a href="#" class="sub">About</a></li>
		</ul>
		<div class="clear"></div>
	</li>
	<li><a href="../TangTret/Sanh1.aspx" class="arrow">Tầng Trệt</a>
	<ul>
		<li><a href="../Tang1/Sanh1.aspx" class="sub">Tầng 1</a></li>
		<li><a href="../Tang2/Sanh1.aspx" class="sub">Tầng 2</a></li>
	</ul>
		<div class="clear"></div>
	</li>
	<li><a class="arrow current">2D</a>
	<ul>
		<li><a href="../3D/TangTret/Sanh2.aspx" class="sub">3D</a></li>
	</ul>
		<div class="clear"></div>
	</li>
</ul>

<!--HTML SNIPPET GENERATED BY GIMP

WARNING!! This is NOT a fully valid HTML document, it is rather a piece of
HTML generated by GIMP's py-slice plugin that should be embedded in an HTML
or XHTML document to be valid.

Replace the href targets in the anchor (<a >) for your URLS to have it working
as a menu.
 -->
<div style="width:800px;">
<div style="width:70%; float:left;">
<asp:Label ID="lblNavigation" runat="server" Text="Định Hướng"></asp:Label>
<br clear="all"/>
<div style="float:left; width:27%;">
<table cellpadding="0" border="0" cellspacing="0">
  <tr>
    <td><a href="Sanh1.aspx"><img alt="" src="../../images/ThamQuan/TangTret/Sanh2/struct/slice_0_0.jpg" style="width: 73px; height: 150px; border-width: 0px" 
name="0_0" 
/></a></td>

    <td><a href="Sanh2.aspx"><img alt="" src="../../images/ThamQuan/TangTret/Sanh2/struct/slice_0_1.jpg" style="width: 77px; height: 150px; border-width: 0px" 
name="0_1" 
/></a></td>

</tr>

</table>
</div>

<div style="float:left; width:25%;">
<table cellpadding="0" border="0" cellspacing="0">
<tr>
    <td>
	<ul>
    <h4 style="color:Black; font-weight:bold; margin-right:20px"> TẦNG TRỆT</h4>
	<li><a  style="text-decoration:none" href="Sanh1.aspx">1: Sảnh 1</a></li>
	<li style="color:Black">2: Sảnh 2</li>
	</ul>
    </td>
</tr>
</table>
</div>

<div style="float:left; width:33%;">
<table cellpadding="0" border="0" cellspacing="0">
  <tr>
    <td><a href="Sanh1.aspx"><img alt=" " src="../../images/ThamQuan/TangTret/Sanh2/navigate/slice_0_0.jpg"  style="width: 110px; height: 119px; border-width: 0px;"/></a></td>
    <td><a><img alt=" " src="../../images/ThamQuan/TangTret/Sanh2/navigate/slice_0_1.jpg"  style="width: 79px; height: 119px; border-width: 0px;"/></a></td>
</tr>

</table>
</div>

</div>
<div style="width:30%; float:left;">
<asp:Label ID="lblOption" runat="server" Text="Tùy Chọn"></asp:Label>
<br clear="all"/>
<div style="float:left;">
<asp:Menu ID="mnuTang" runat="server" CssClass="menu" EnableViewState="false" 
        IncludeStyleBlock="false">
    <Items>
        <asp:MenuItem NavigateUrl="../Tang2/Sanh1.aspx" Text="Tầng 2"/>
        <asp:MenuItem NavigateUrl="../Tang1/Sanh1.aspx" Text="Tầng 1"/>
        <asp:MenuItem NavigateUrl="../TangTret/Sanh1.aspx" Text="Tầng Trệt"/>
    </Items>
</asp:Menu>
</div>
<div style="float:left;">
<asp:Menu ID="mnuCheDo" runat="server" CssClass="menu" EnableViewState="false" 
        IncludeStyleBlock="false">
    <Items>
        <asp:MenuItem NavigateUrl="../TangTret/Sanh2.aspx" Text="2D"/>
        <asp:MenuItem NavigateUrl="../3D/TangTret/Sanh2.aspx" Text="3D"/>
    </Items>
</asp:Menu>
</div>
</div>

 <div id="container">
  
      <!--  Outer wrapper for presentation only, this can be anything you like -->
      <div id="banner">
        <!-- start Basic Jquery Slider -->
        <ul class="bjqs">
          <li><img src="../../images/ThamQuan/TangTret/Sanh2/img/banner01.jpg" title="Automatically generated caption"/></li>
          <li><img src="../../images/ThamQuan/TangTret/Sanh2/img/banner02.jpg" title="Automatically generated caption"/></li>
          <li><img src="../../images/ThamQuan/TangTret/Sanh2/img/banner03.jpg" title="Automatically generated caption"/></li>
        </ul>
        <!-- end Basic jQuery Slider -->
      </div>
      <!-- End outer wrapper -->
      
    </div>
  
    <!-- Load jQuery and the plug-in -->
    <script type="text/javascript" src="../../Scripts/basic-jquery-slider.js"></script>
    
    <!--  Attach the plug-in to the slider parent element and adjust the settings as required -->
    <script type="text/javascript">
        $(document).ready(function () {

            $('#banner').bjqs({
                'animation': 'slide',
                'width': 582,
                'height': 385
            });

        });
    </script>
</div>

<!--
End of the part generated by GIMP
-->


</asp:Content>
