<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="ChonTang.aspx.cs" Inherits="WARM.WebForm1" %>
<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" runat="server">
    <script type="text/javascript" src="../../Scripts/jquery.js"></script>
    <script type="text/javascript" src="../../Scripts/jquery-ui.min.js"></script>
    <script type="text/javascript" src="../../Scripts/bootstrap.js"></script>
    <script type="text/javascript" src="../../Scripts/bootstrap.min.js"></script>
    <script type="text/javascript" src="../../Scripts/breadcrumbs.js"></script>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">

<ul id="nav">
	<li><a href="..">Trang Chủ > </a></li>
	<li><a href="#" class="arrow">Tham Quan > </a>
		<ul>
			<li><a href="#" class="sub">Đăng Ký</a></li>
			<li><a href="#" class="sub">Đặt Bàn</a></li>
			<li><a href="#" class="sub">Đặt Món</a></li>
			<li><a href="#" class="sub">Chi Tiết Món</a></li>
			<li><a href="#" class="sub">About</a></li>
		</ul>
		<div class="clear"></div>
	</li>
	<li><a class="arrow current">Chọn Tầng</a>
	<ul>
		<li><a href="TangTret/Sanh1.aspx" class="sub">Tầng Trệt</a></li>
		<li><a href="Tang1/Sanh1.aspx" class="sub">Tầng 1</a></li>
		<li><a href="Tang2/Sanh1.aspx" class="sub">Tầng 2</a></li>
	</ul>
		<div class="clear"></div>
	</li>
</ul>
<!--HTML SNIPPET GENERATED BY GIMP

WARNING!! This is NOT a fully valid HTML document, it is rather a piece of
HTML generated by GIMP's py-slice plugin that should be embedded in an HTML
or XHTML document to be valid.

Replace the href targets in the anchor (<a >) for your URLS to have it working
as a menu.
    -->
    <div style="width:70%; float:left;">
<table cellpadding="0" border="0" cellspacing="0">
    <tr><td style="background-image: url(../images/ThamQuan/ChonTang/slice_0_0.jpg); height: 150px; width: 204px;"></td>
    <td style="background-image: url(../images/ThamQuan/ChonTang/slice_0_1.jpg); height: 150px; width: 267px;"></td>
    <td style="background-image: url(../images/ThamQuan/ChonTang/slice_0_2.jpg); height: 150px; width: 129px;"></td></tr>

    <tr><td style="background-image: url(../images/ThamQuan/ChonTang/slice_1_0.jpg); height: 60px; width: 204px;"></td>
    <td style="background-image: url(../images/ThamQuan/ChonTang/slice_1_1-new.jpg); height: 60px; width: 267px;" onMouseOver="exchange(this,images_slice,explains,1);" onMouseOut="exchange(this,images_slice,explains,0);" onClick="exchange(this,images_slice,explains,2);" id="1_1"></td>
    <td style="background-image: url(../images/ThamQuan/ChonTang/slice_1_2.jpg); height: 60px; width: 129px;"></td></tr>

    <tr><td style="background-image: url(../images/ThamQuan/ChonTang/slice_2_0.jpg); height: 29px; width: 204px;"></td>
    <td style="background-image: url(../images/ThamQuan/ChonTang/slice_2_1.jpg); height: 29px; width: 267px;"></td>
    <td style="background-image: url(../images/ThamQuan/ChonTang/slice_2_2.jpg); height: 29px; width: 129px;"></td></tr>

    <tr><td style="background-image: url(../images/ThamQuan/ChonTang/slice_3_0.jpg); height: 56px; width: 204px;"></td>
    <td style="background-image: url(../images/ThamQuan/ChonTang/slice_3_1-new.jpg); height: 56px; width: 267px;" onMouseOver="exchange(this,images_slice,explains,1);" onMouseOut="exchange(this,images_slice,explains,0);" onClick="exchange(this,images_slice,explains,2);" id="3_1"></td>
    <td style="background-image: url(../images/ThamQuan/ChonTang/slice_3_2.jpg); height: 56px; width: 129px;"></td></tr>

    <tr><td style="background-image: url(../images/ThamQuan/ChonTang/slice_4_0.jpg); height: 27px; width: 204px;"></td>
    <td style="background-image: url(../images/ThamQuan/ChonTang/slice_4_1.jpg); height: 27px; width: 267px;"></td>
    <td style="background-image: url(../images/ThamQuan/ChonTang/slice_4_2.jpg); height: 27px; width: 129px;"></td></tr>

    <tr><td style="background-image: url(../images/ThamQuan/ChonTang/slice_5_0.jpg); height: 72px; width: 204px;"></td>
    <td style="background-image: url(../images/ThamQuan/ChonTang/slice_5_1-new.jpg); height: 72px; width: 267px;" onMouseOver="exchange(this,images_slice,explains,1);" onMouseOut="exchange(this,images_slice,explains,0);" onClick="exchange(this,images_slice,explains,2);" id="5_1"></td>
    <td style="background-image: url(../images/ThamQuan/ChonTang/slice_5_2.jpg); height: 72px; width: 129px;"></td></tr>

    <tr><td style="background-image: url(../images/ThamQuan/ChonTang/slice_6_0.jpg); height: 57px; width: 204px;"></td>
    <td style="background-image: url(../images/ThamQuan/ChonTang/slice_6_1.jpg); height: 57px; width: 267px;"></td>
    <td style="background-image: url(../images/ThamQuan/ChonTang/slice_6_2.jpg); height: 57px; width: 129px;"></td></tr>
</table>

<div class="popupMenu" id="5_1_PopupMenu" 
            style="position: absolute; visibility: hidden; left: 827px; top: 508px; z-index: 1000;">
    <div style="border:1px outset white;padding:2px;">
    <a href="TangTret/Sanh1.aspx"><div style="background-image: url(../images/ThamQuan/ChonTang/slice_0_0_menu.png); height: 42px; width: 124px;"></div></a>
    <a href="3D/TangTret/Sanh1.aspx"><div style="background-image: url(../images/ThamQuan/ChonTang/slice_1_0_menu.png); width: 124px; height: 44px;"></div></a>
    </div>
</div>

<div class="popupMenu" id="3_1_PopupMenu" 
            style="position: absolute; visibility: hidden; left: 828px; top: 415px; z-index: 1000;">
    <div style="border:1px outset white;padding:2px;">
    <a href="Tang1/Sanh1.aspx"><div style="background-image: url(../images/ThamQuan/ChonTang/slice_0_0_menu.png); height: 42px; width: 124px;"></div></a>
    <a href="3D/Tang1/Sanh1.aspx"><div style="background-image: url(../images/ThamQuan/ChonTang/slice_1_0_menu.png); width: 124px; height: 44px;"></div></a>
    </div>
</div>

<div class="popupMenu" id="1_1_PopupMenu" 
            style="position: absolute; visibility: hidden; left: 823px; top: 326px; z-index: 1000;">
    <div style="border:1px outset white;padding:2px;">
    <a href="Tang2/Sanh1.aspx"><div style="background-image: url(../images/ThamQuan/ChonTang/slice_0_0_menu.png); height: 42px; width: 124px;"></div></a>
    <a href="3D/Tang2/Sanh1.aspx"><div style="background-image: url(../images/ThamQuan/ChonTang/slice_1_0_menu.png); width: 124px; height: 44px;"></div></a>
    </div>
</div>

</div>

    <div style="width:15%; height: 300px; float:left;">
    <h1>Kiến Trúc</h1>
    <table cellpadding="0" border="0" cellspacing="0">
    <tr>
        <td id="struct_image" style="background-image: url(../images/ThamQuan/ChonTang/struct.jpg); width:100px; height:100px;"></td>
    </tr>
    <tr>
        <td>
	    <ul id="explain">
	    </ul>
        </td>
    </tr>
    </table>
</div>

<script language="javascript" type="text/javascript">
    /* Made with GIMP */

    /* Preload images: */
    images_slice = new Array();

    images_slice["1_1_plain"] = "url(../images/ThamQuan/ChonTang/slice_1_1-new.jpg)";
    images_slice["3_1_plain"] = "url(../images/ThamQuan/ChonTang/slice_3_1-new.jpg)";
    images_slice["5_1_plain"] = "url(../images/ThamQuan/ChonTang/slice_5_1-new.jpg)";

    images_slice["1_1_hover"] = "url(../images/ThamQuan/ChonTang/slice_1_1_hover.jpg)";

    images_slice["3_1_hover"] = "url(../images/ThamQuan/ChonTang/slice_3_1_hover.jpg)";

    images_slice["5_1_hover"] = "url(../images/ThamQuan/ChonTang/slice_5_1_hover.jpg)";

    images_slice["1_1_struct"] = "url(../images/ThamQuan/ChonTang/1_1_struct.jpg)";
    images_slice["3_1_struct"] = "url(../images/ThamQuan/ChonTang/3_1_struct.jpg)";
    images_slice["5_1_struct"] = "url(../images/ThamQuan/ChonTang/5_1_struct.jpg)";

    explains = new Array();

    explains["1_1"] =
	"<li><a>1: Sanh 1</a></li>\
	<li><a>2: Sanh 2</a></li>\
	<li><a>3: Sanh 3</a></li>\
	<li><a>4: Sanh 4</a></li>";
    explains["3_1"] =
	"<li><a>1: Sanh 1</a></li>\
	<li><a>2: Sanh 2</a></li>\
	<li><a>3: Sanh 3</a></li>";
    explains["5_1"] =
	"<li><a>1: Sanh 1</a></li>\
	<li><a>2: Sanh 2</a></li>";
    explains["empty"] =
	"";

    function exchange(image, images_array_name, explains_array, event) {
        name = image.id;
        images = eval(images_array_name);
        explains = eval(explains_array);

        switch (event) {
            case 0:
                image.style.backgroundImage = images[name + "_plain"];
                //document.getElementById("struct_image").style.backgroundImage = "url(../images/ThamQuan/ChonTang/struct.jpg)";
                //document.getElementById("explain").innerHTML = explains["empty"];
                //$("#"+name+"_PopupMenu").css("visibility", "hidden"); 
                break;
            case 1:
                image.style.backgroundImage = images[name + "_hover"];
                document.getElementById("struct_image").style.backgroundImage = images[name + "_struct"];
                document.getElementById("explain").innerHTML = explains[name];
                break;
            case 2:
                //image.src = images[name + "_clicked"].src;
                if ($("#" + name + "_PopupMenu").css("visibility") == "hidden")
                    $("#" + name + "_PopupMenu").css("visibility", "visible");
                else
                    $("#" + name + "_PopupMenu").css("visibility", "hidden");
                break;
            case 3:
                image.style.backgroundImage = images[name + "_hover"];
                break;
        }

    }
</script>
<!--
End of the part generated by GIMP
-->

</asp:Content>
