#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLNhaHang")]
	public partial class QLNhaHangDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBANAN(BANAN instance);
    partial void UpdateBANAN(BANAN instance);
    partial void DeleteBANAN(BANAN instance);
    partial void InsertTINHTRANGPHIEU(TINHTRANGPHIEU instance);
    partial void UpdateTINHTRANGPHIEU(TINHTRANGPHIEU instance);
    partial void DeleteTINHTRANGPHIEU(TINHTRANGPHIEU instance);
    partial void InsertCHITIETPHIEU(CHITIETPHIEU instance);
    partial void UpdateCHITIETPHIEU(CHITIETPHIEU instance);
    partial void DeleteCHITIETPHIEU(CHITIETPHIEU instance);
    partial void InsertDANHMUCBANAN(DANHMUCBANAN instance);
    partial void UpdateDANHMUCBANAN(DANHMUCBANAN instance);
    partial void DeleteDANHMUCBANAN(DANHMUCBANAN instance);
    partial void InsertDANHMUCMONAN(DANHMUCMONAN instance);
    partial void UpdateDANHMUCMONAN(DANHMUCMONAN instance);
    partial void DeleteDANHMUCMONAN(DANHMUCMONAN instance);
    partial void InsertLOAINGUOIDUNG(LOAINGUOIDUNG instance);
    partial void UpdateLOAINGUOIDUNG(LOAINGUOIDUNG instance);
    partial void DeleteLOAINGUOIDUNG(LOAINGUOIDUNG instance);
    partial void InsertMONAN(MONAN instance);
    partial void UpdateMONAN(MONAN instance);
    partial void DeleteMONAN(MONAN instance);
    partial void InsertNGUOIDUNG(NGUOIDUNG instance);
    partial void UpdateNGUOIDUNG(NGUOIDUNG instance);
    partial void DeleteNGUOIDUNG(NGUOIDUNG instance);
    partial void InsertPHIEUDATCHO(PHIEUDATCHO instance);
    partial void UpdatePHIEUDATCHO(PHIEUDATCHO instance);
    partial void DeletePHIEUDATCHO(PHIEUDATCHO instance);
    partial void InsertBINHLUAN(BINHLUAN instance);
    partial void UpdateBINHLUAN(BINHLUAN instance);
    partial void DeleteBINHLUAN(BINHLUAN instance);
    #endregion
		
		public QLNhaHangDataContext() : base(global::DAO.Properties.Settings.Default.QLNhaHangConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QLNhaHangDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLNhaHangDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLNhaHangDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLNhaHangDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BANAN> BANANs
		{
			get
			{
				return this.GetTable<BANAN>();
			}
		}
		
		public System.Data.Linq.Table<TINHTRANGPHIEU> TINHTRANGPHIEUs
		{
			get
			{
				return this.GetTable<TINHTRANGPHIEU>();
			}
		}
		
		public System.Data.Linq.Table<CHITIETPHIEU> CHITIETPHIEUs
		{
			get
			{
				return this.GetTable<CHITIETPHIEU>();
			}
		}
		
		public System.Data.Linq.Table<DANHMUCBANAN> DANHMUCBANANs
		{
			get
			{
				return this.GetTable<DANHMUCBANAN>();
			}
		}
		
		public System.Data.Linq.Table<DANHMUCMONAN> DANHMUCMONANs
		{
			get
			{
				return this.GetTable<DANHMUCMONAN>();
			}
		}
		
		public System.Data.Linq.Table<LOAINGUOIDUNG> LOAINGUOIDUNGs
		{
			get
			{
				return this.GetTable<LOAINGUOIDUNG>();
			}
		}
		
		public System.Data.Linq.Table<MONAN> MONANs
		{
			get
			{
				return this.GetTable<MONAN>();
			}
		}
		
		public System.Data.Linq.Table<NGUOIDUNG> NGUOIDUNGs
		{
			get
			{
				return this.GetTable<NGUOIDUNG>();
			}
		}
		
		public System.Data.Linq.Table<PHIEUDATCHO> PHIEUDATCHOs
		{
			get
			{
				return this.GetTable<PHIEUDATCHO>();
			}
		}
		
		public System.Data.Linq.Table<BINHLUAN> BINHLUANs
		{
			get
			{
				return this.GetTable<BINHLUAN>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BANAN")]
	public partial class BANAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaBan;
		
		private string _TenBan;
		
		private System.Nullable<int> _MaDMBanAn;
		
		private string _Anh;
		
		private System.Nullable<bool> _DaXoa;
		
		private System.Nullable<bool> _ConBan;
		
		private EntitySet<PHIEUDATCHO> _PHIEUDATCHOs;
		
		private EntityRef<DANHMUCBANAN> _DANHMUCBANAN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaBanChanging(int value);
    partial void OnMaBanChanged();
    partial void OnTenBanChanging(string value);
    partial void OnTenBanChanged();
    partial void OnMaDMBanAnChanging(System.Nullable<int> value);
    partial void OnMaDMBanAnChanged();
    partial void OnAnhChanging(string value);
    partial void OnAnhChanged();
    partial void OnDaXoaChanging(System.Nullable<bool> value);
    partial void OnDaXoaChanged();
    partial void OnConBanChanging(System.Nullable<bool> value);
    partial void OnConBanChanged();
    #endregion
		
		public BANAN()
		{
			this._PHIEUDATCHOs = new EntitySet<PHIEUDATCHO>(new Action<PHIEUDATCHO>(this.attach_PHIEUDATCHOs), new Action<PHIEUDATCHO>(this.detach_PHIEUDATCHOs));
			this._DANHMUCBANAN = default(EntityRef<DANHMUCBANAN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBan", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaBan
		{
			get
			{
				return this._MaBan;
			}
			set
			{
				if ((this._MaBan != value))
				{
					this.OnMaBanChanging(value);
					this.SendPropertyChanging();
					this._MaBan = value;
					this.SendPropertyChanged("MaBan");
					this.OnMaBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenBan", DbType="NVarChar(50)")]
		public string TenBan
		{
			get
			{
				return this._TenBan;
			}
			set
			{
				if ((this._TenBan != value))
				{
					this.OnTenBanChanging(value);
					this.SendPropertyChanging();
					this._TenBan = value;
					this.SendPropertyChanged("TenBan");
					this.OnTenBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDMBanAn", DbType="Int")]
		public System.Nullable<int> MaDMBanAn
		{
			get
			{
				return this._MaDMBanAn;
			}
			set
			{
				if ((this._MaDMBanAn != value))
				{
					if (this._DANHMUCBANAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDMBanAnChanging(value);
					this.SendPropertyChanging();
					this._MaDMBanAn = value;
					this.SendPropertyChanged("MaDMBanAn");
					this.OnMaDMBanAnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Anh", DbType="VarChar(150)")]
		public string Anh
		{
			get
			{
				return this._Anh;
			}
			set
			{
				if ((this._Anh != value))
				{
					this.OnAnhChanging(value);
					this.SendPropertyChanging();
					this._Anh = value;
					this.SendPropertyChanged("Anh");
					this.OnAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaXoa", DbType="Bit")]
		public System.Nullable<bool> DaXoa
		{
			get
			{
				return this._DaXoa;
			}
			set
			{
				if ((this._DaXoa != value))
				{
					this.OnDaXoaChanging(value);
					this.SendPropertyChanging();
					this._DaXoa = value;
					this.SendPropertyChanged("DaXoa");
					this.OnDaXoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConBan", DbType="Bit")]
		public System.Nullable<bool> ConBan
		{
			get
			{
				return this._ConBan;
			}
			set
			{
				if ((this._ConBan != value))
				{
					this.OnConBanChanging(value);
					this.SendPropertyChanging();
					this._ConBan = value;
					this.SendPropertyChanged("ConBan");
					this.OnConBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BANAN_PHIEUDATCHO", Storage="_PHIEUDATCHOs", ThisKey="MaBan", OtherKey="MaBanAn")]
		public EntitySet<PHIEUDATCHO> PHIEUDATCHOs
		{
			get
			{
				return this._PHIEUDATCHOs;
			}
			set
			{
				this._PHIEUDATCHOs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DANHMUCBANAN_BANAN", Storage="_DANHMUCBANAN", ThisKey="MaDMBanAn", OtherKey="MaDMBanAn", IsForeignKey=true)]
		public DANHMUCBANAN DANHMUCBANAN
		{
			get
			{
				return this._DANHMUCBANAN.Entity;
			}
			set
			{
				DANHMUCBANAN previousValue = this._DANHMUCBANAN.Entity;
				if (((previousValue != value) 
							|| (this._DANHMUCBANAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DANHMUCBANAN.Entity = null;
						previousValue.BANANs.Remove(this);
					}
					this._DANHMUCBANAN.Entity = value;
					if ((value != null))
					{
						value.BANANs.Add(this);
						this._MaDMBanAn = value.MaDMBanAn;
					}
					else
					{
						this._MaDMBanAn = default(Nullable<int>);
					}
					this.SendPropertyChanged("DANHMUCBANAN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PHIEUDATCHOs(PHIEUDATCHO entity)
		{
			this.SendPropertyChanging();
			entity.BANAN = this;
		}
		
		private void detach_PHIEUDATCHOs(PHIEUDATCHO entity)
		{
			this.SendPropertyChanging();
			entity.BANAN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TINHTRANGPHIEU")]
	public partial class TINHTRANGPHIEU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaTinhTrangPhieu;
		
		private string _Ten;
		
		private EntitySet<PHIEUDATCHO> _PHIEUDATCHOs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTinhTrangPhieuChanging(int value);
    partial void OnMaTinhTrangPhieuChanged();
    partial void OnTenChanging(string value);
    partial void OnTenChanged();
    #endregion
		
		public TINHTRANGPHIEU()
		{
			this._PHIEUDATCHOs = new EntitySet<PHIEUDATCHO>(new Action<PHIEUDATCHO>(this.attach_PHIEUDATCHOs), new Action<PHIEUDATCHO>(this.detach_PHIEUDATCHOs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTinhTrangPhieu", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaTinhTrangPhieu
		{
			get
			{
				return this._MaTinhTrangPhieu;
			}
			set
			{
				if ((this._MaTinhTrangPhieu != value))
				{
					this.OnMaTinhTrangPhieuChanging(value);
					this.SendPropertyChanging();
					this._MaTinhTrangPhieu = value;
					this.SendPropertyChanged("MaTinhTrangPhieu");
					this.OnMaTinhTrangPhieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Ten
		{
			get
			{
				return this._Ten;
			}
			set
			{
				if ((this._Ten != value))
				{
					this.OnTenChanging(value);
					this.SendPropertyChanging();
					this._Ten = value;
					this.SendPropertyChanged("Ten");
					this.OnTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TINHTRANGPHIEU_PHIEUDATCHO", Storage="_PHIEUDATCHOs", ThisKey="MaTinhTrangPhieu", OtherKey="MaTinhTrangPhieu")]
		public EntitySet<PHIEUDATCHO> PHIEUDATCHOs
		{
			get
			{
				return this._PHIEUDATCHOs;
			}
			set
			{
				this._PHIEUDATCHOs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PHIEUDATCHOs(PHIEUDATCHO entity)
		{
			this.SendPropertyChanging();
			entity.TINHTRANGPHIEU = this;
		}
		
		private void detach_PHIEUDATCHOs(PHIEUDATCHO entity)
		{
			this.SendPropertyChanging();
			entity.TINHTRANGPHIEU = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHITIETPHIEU")]
	public partial class CHITIETPHIEU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaChiTietPhieu;
		
		private System.Nullable<int> _MaPhieu;
		
		private System.Nullable<int> _MaMonAn;
		
		private System.Nullable<int> _SoLuong;
		
		private EntityRef<MONAN> _MONAN;
		
		private EntityRef<PHIEUDATCHO> _PHIEUDATCHO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaChiTietPhieuChanging(int value);
    partial void OnMaChiTietPhieuChanged();
    partial void OnMaPhieuChanging(System.Nullable<int> value);
    partial void OnMaPhieuChanged();
    partial void OnMaMonAnChanging(System.Nullable<int> value);
    partial void OnMaMonAnChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    #endregion
		
		public CHITIETPHIEU()
		{
			this._MONAN = default(EntityRef<MONAN>);
			this._PHIEUDATCHO = default(EntityRef<PHIEUDATCHO>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaChiTietPhieu", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaChiTietPhieu
		{
			get
			{
				return this._MaChiTietPhieu;
			}
			set
			{
				if ((this._MaChiTietPhieu != value))
				{
					this.OnMaChiTietPhieuChanging(value);
					this.SendPropertyChanging();
					this._MaChiTietPhieu = value;
					this.SendPropertyChanged("MaChiTietPhieu");
					this.OnMaChiTietPhieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhieu", DbType="Int")]
		public System.Nullable<int> MaPhieu
		{
			get
			{
				return this._MaPhieu;
			}
			set
			{
				if ((this._MaPhieu != value))
				{
					if (this._PHIEUDATCHO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaPhieuChanging(value);
					this.SendPropertyChanging();
					this._MaPhieu = value;
					this.SendPropertyChanged("MaPhieu");
					this.OnMaPhieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMonAn", DbType="Int")]
		public System.Nullable<int> MaMonAn
		{
			get
			{
				return this._MaMonAn;
			}
			set
			{
				if ((this._MaMonAn != value))
				{
					if (this._MONAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaMonAnChanging(value);
					this.SendPropertyChanging();
					this._MaMonAn = value;
					this.SendPropertyChanged("MaMonAn");
					this.OnMaMonAnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MONAN_CHITIETPHIEU", Storage="_MONAN", ThisKey="MaMonAn", OtherKey="MaMonAn", IsForeignKey=true)]
		public MONAN MONAN
		{
			get
			{
				return this._MONAN.Entity;
			}
			set
			{
				MONAN previousValue = this._MONAN.Entity;
				if (((previousValue != value) 
							|| (this._MONAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MONAN.Entity = null;
						previousValue.CHITIETPHIEUs.Remove(this);
					}
					this._MONAN.Entity = value;
					if ((value != null))
					{
						value.CHITIETPHIEUs.Add(this);
						this._MaMonAn = value.MaMonAn;
					}
					else
					{
						this._MaMonAn = default(Nullable<int>);
					}
					this.SendPropertyChanged("MONAN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHIEUDATCHO_CHITIETPHIEU", Storage="_PHIEUDATCHO", ThisKey="MaPhieu", OtherKey="MaPhieu", IsForeignKey=true)]
		public PHIEUDATCHO PHIEUDATCHO
		{
			get
			{
				return this._PHIEUDATCHO.Entity;
			}
			set
			{
				PHIEUDATCHO previousValue = this._PHIEUDATCHO.Entity;
				if (((previousValue != value) 
							|| (this._PHIEUDATCHO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PHIEUDATCHO.Entity = null;
						previousValue.CHITIETPHIEUs.Remove(this);
					}
					this._PHIEUDATCHO.Entity = value;
					if ((value != null))
					{
						value.CHITIETPHIEUs.Add(this);
						this._MaPhieu = value.MaPhieu;
					}
					else
					{
						this._MaPhieu = default(Nullable<int>);
					}
					this.SendPropertyChanged("PHIEUDATCHO");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DANHMUCBANAN")]
	public partial class DANHMUCBANAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaDMBanAn;
		
		private string _Ten;
		
		private string _Anh;
		
		private System.Nullable<bool> _DaXoa;
		
		private string _MoTa;
		
		private EntitySet<BANAN> _BANANs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDMBanAnChanging(int value);
    partial void OnMaDMBanAnChanged();
    partial void OnTenChanging(string value);
    partial void OnTenChanged();
    partial void OnAnhChanging(string value);
    partial void OnAnhChanged();
    partial void OnDaXoaChanging(System.Nullable<bool> value);
    partial void OnDaXoaChanged();
    partial void OnMoTaChanging(string value);
    partial void OnMoTaChanged();
    #endregion
		
		public DANHMUCBANAN()
		{
			this._BANANs = new EntitySet<BANAN>(new Action<BANAN>(this.attach_BANANs), new Action<BANAN>(this.detach_BANANs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDMBanAn", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaDMBanAn
		{
			get
			{
				return this._MaDMBanAn;
			}
			set
			{
				if ((this._MaDMBanAn != value))
				{
					this.OnMaDMBanAnChanging(value);
					this.SendPropertyChanging();
					this._MaDMBanAn = value;
					this.SendPropertyChanged("MaDMBanAn");
					this.OnMaDMBanAnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten", DbType="NVarChar(50)")]
		public string Ten
		{
			get
			{
				return this._Ten;
			}
			set
			{
				if ((this._Ten != value))
				{
					this.OnTenChanging(value);
					this.SendPropertyChanging();
					this._Ten = value;
					this.SendPropertyChanged("Ten");
					this.OnTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Anh", DbType="VarChar(150)")]
		public string Anh
		{
			get
			{
				return this._Anh;
			}
			set
			{
				if ((this._Anh != value))
				{
					this.OnAnhChanging(value);
					this.SendPropertyChanging();
					this._Anh = value;
					this.SendPropertyChanged("Anh");
					this.OnAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaXoa", DbType="Bit")]
		public System.Nullable<bool> DaXoa
		{
			get
			{
				return this._DaXoa;
			}
			set
			{
				if ((this._DaXoa != value))
				{
					this.OnDaXoaChanging(value);
					this.SendPropertyChanging();
					this._DaXoa = value;
					this.SendPropertyChanged("DaXoa");
					this.OnDaXoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NVarChar(400)")]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this.OnMoTaChanging(value);
					this.SendPropertyChanging();
					this._MoTa = value;
					this.SendPropertyChanged("MoTa");
					this.OnMoTaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DANHMUCBANAN_BANAN", Storage="_BANANs", ThisKey="MaDMBanAn", OtherKey="MaDMBanAn")]
		public EntitySet<BANAN> BANANs
		{
			get
			{
				return this._BANANs;
			}
			set
			{
				this._BANANs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BANANs(BANAN entity)
		{
			this.SendPropertyChanging();
			entity.DANHMUCBANAN = this;
		}
		
		private void detach_BANANs(BANAN entity)
		{
			this.SendPropertyChanging();
			entity.DANHMUCBANAN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DANHMUCMONAN")]
	public partial class DANHMUCMONAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaDMMonAn;
		
		private string _Ten;
		
		private string _Anh;
		
		private System.Nullable<bool> _DaXoa;
		
		private EntitySet<MONAN> _MONANs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDMMonAnChanging(int value);
    partial void OnMaDMMonAnChanged();
    partial void OnTenChanging(string value);
    partial void OnTenChanged();
    partial void OnAnhChanging(string value);
    partial void OnAnhChanged();
    partial void OnDaXoaChanging(System.Nullable<bool> value);
    partial void OnDaXoaChanged();
    #endregion
		
		public DANHMUCMONAN()
		{
			this._MONANs = new EntitySet<MONAN>(new Action<MONAN>(this.attach_MONANs), new Action<MONAN>(this.detach_MONANs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDMMonAn", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaDMMonAn
		{
			get
			{
				return this._MaDMMonAn;
			}
			set
			{
				if ((this._MaDMMonAn != value))
				{
					this.OnMaDMMonAnChanging(value);
					this.SendPropertyChanging();
					this._MaDMMonAn = value;
					this.SendPropertyChanged("MaDMMonAn");
					this.OnMaDMMonAnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten", DbType="NVarChar(50)")]
		public string Ten
		{
			get
			{
				return this._Ten;
			}
			set
			{
				if ((this._Ten != value))
				{
					this.OnTenChanging(value);
					this.SendPropertyChanging();
					this._Ten = value;
					this.SendPropertyChanged("Ten");
					this.OnTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Anh", DbType="VarChar(150)")]
		public string Anh
		{
			get
			{
				return this._Anh;
			}
			set
			{
				if ((this._Anh != value))
				{
					this.OnAnhChanging(value);
					this.SendPropertyChanging();
					this._Anh = value;
					this.SendPropertyChanged("Anh");
					this.OnAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaXoa", DbType="Bit")]
		public System.Nullable<bool> DaXoa
		{
			get
			{
				return this._DaXoa;
			}
			set
			{
				if ((this._DaXoa != value))
				{
					this.OnDaXoaChanging(value);
					this.SendPropertyChanging();
					this._DaXoa = value;
					this.SendPropertyChanged("DaXoa");
					this.OnDaXoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DANHMUCMONAN_MONAN", Storage="_MONANs", ThisKey="MaDMMonAn", OtherKey="MaDMMonAn")]
		public EntitySet<MONAN> MONANs
		{
			get
			{
				return this._MONANs;
			}
			set
			{
				this._MONANs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_MONANs(MONAN entity)
		{
			this.SendPropertyChanging();
			entity.DANHMUCMONAN = this;
		}
		
		private void detach_MONANs(MONAN entity)
		{
			this.SendPropertyChanging();
			entity.DANHMUCMONAN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOAINGUOIDUNG")]
	public partial class LOAINGUOIDUNG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaLoaiNguoiDung;
		
		private string _TenLoaiNguoiDung;
		
		private EntitySet<NGUOIDUNG> _NGUOIDUNGs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLoaiNguoiDungChanging(int value);
    partial void OnMaLoaiNguoiDungChanged();
    partial void OnTenLoaiNguoiDungChanging(string value);
    partial void OnTenLoaiNguoiDungChanged();
    #endregion
		
		public LOAINGUOIDUNG()
		{
			this._NGUOIDUNGs = new EntitySet<NGUOIDUNG>(new Action<NGUOIDUNG>(this.attach_NGUOIDUNGs), new Action<NGUOIDUNG>(this.detach_NGUOIDUNGs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiNguoiDung", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaLoaiNguoiDung
		{
			get
			{
				return this._MaLoaiNguoiDung;
			}
			set
			{
				if ((this._MaLoaiNguoiDung != value))
				{
					this.OnMaLoaiNguoiDungChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiNguoiDung = value;
					this.SendPropertyChanged("MaLoaiNguoiDung");
					this.OnMaLoaiNguoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoaiNguoiDung", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenLoaiNguoiDung
		{
			get
			{
				return this._TenLoaiNguoiDung;
			}
			set
			{
				if ((this._TenLoaiNguoiDung != value))
				{
					this.OnTenLoaiNguoiDungChanging(value);
					this.SendPropertyChanging();
					this._TenLoaiNguoiDung = value;
					this.SendPropertyChanged("TenLoaiNguoiDung");
					this.OnTenLoaiNguoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAINGUOIDUNG_NGUOIDUNG", Storage="_NGUOIDUNGs", ThisKey="MaLoaiNguoiDung", OtherKey="MaLoaiNguoiDung")]
		public EntitySet<NGUOIDUNG> NGUOIDUNGs
		{
			get
			{
				return this._NGUOIDUNGs;
			}
			set
			{
				this._NGUOIDUNGs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NGUOIDUNGs(NGUOIDUNG entity)
		{
			this.SendPropertyChanging();
			entity.LOAINGUOIDUNG = this;
		}
		
		private void detach_NGUOIDUNGs(NGUOIDUNG entity)
		{
			this.SendPropertyChanging();
			entity.LOAINGUOIDUNG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MONAN")]
	public partial class MONAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaMonAn;
		
		private string _TenMonAn;
		
		private string _MoTa;
		
		private System.Nullable<double> _Gia;
		
		private System.Nullable<int> _MaDMMonAn;
		
		private string _Anh;
		
		private System.Nullable<int> _DanhGia;
		
		private System.Nullable<bool> _DaXoa;
		
		private System.Nullable<bool> _ConMon;
		
		private EntitySet<CHITIETPHIEU> _CHITIETPHIEUs;
		
		private EntitySet<BINHLUAN> _BINHLUANs;
		
		private EntityRef<DANHMUCMONAN> _DANHMUCMONAN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaMonAnChanging(int value);
    partial void OnMaMonAnChanged();
    partial void OnTenMonAnChanging(string value);
    partial void OnTenMonAnChanged();
    partial void OnMoTaChanging(string value);
    partial void OnMoTaChanged();
    partial void OnGiaChanging(System.Nullable<double> value);
    partial void OnGiaChanged();
    partial void OnMaDMMonAnChanging(System.Nullable<int> value);
    partial void OnMaDMMonAnChanged();
    partial void OnAnhChanging(string value);
    partial void OnAnhChanged();
    partial void OnDanhGiaChanging(System.Nullable<int> value);
    partial void OnDanhGiaChanged();
    partial void OnDaXoaChanging(System.Nullable<bool> value);
    partial void OnDaXoaChanged();
    partial void OnConMonChanging(System.Nullable<bool> value);
    partial void OnConMonChanged();
    #endregion
		
		public MONAN()
		{
			this._CHITIETPHIEUs = new EntitySet<CHITIETPHIEU>(new Action<CHITIETPHIEU>(this.attach_CHITIETPHIEUs), new Action<CHITIETPHIEU>(this.detach_CHITIETPHIEUs));
			this._BINHLUANs = new EntitySet<BINHLUAN>(new Action<BINHLUAN>(this.attach_BINHLUANs), new Action<BINHLUAN>(this.detach_BINHLUANs));
			this._DANHMUCMONAN = default(EntityRef<DANHMUCMONAN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMonAn", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaMonAn
		{
			get
			{
				return this._MaMonAn;
			}
			set
			{
				if ((this._MaMonAn != value))
				{
					this.OnMaMonAnChanging(value);
					this.SendPropertyChanging();
					this._MaMonAn = value;
					this.SendPropertyChanged("MaMonAn");
					this.OnMaMonAnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenMonAn", DbType="NVarChar(150)")]
		public string TenMonAn
		{
			get
			{
				return this._TenMonAn;
			}
			set
			{
				if ((this._TenMonAn != value))
				{
					this.OnTenMonAnChanging(value);
					this.SendPropertyChanging();
					this._TenMonAn = value;
					this.SendPropertyChanged("TenMonAn");
					this.OnTenMonAnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NVarChar(400)")]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this.OnMoTaChanging(value);
					this.SendPropertyChanging();
					this._MoTa = value;
					this.SendPropertyChanged("MoTa");
					this.OnMoTaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gia", DbType="Float")]
		public System.Nullable<double> Gia
		{
			get
			{
				return this._Gia;
			}
			set
			{
				if ((this._Gia != value))
				{
					this.OnGiaChanging(value);
					this.SendPropertyChanging();
					this._Gia = value;
					this.SendPropertyChanged("Gia");
					this.OnGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDMMonAn", DbType="Int")]
		public System.Nullable<int> MaDMMonAn
		{
			get
			{
				return this._MaDMMonAn;
			}
			set
			{
				if ((this._MaDMMonAn != value))
				{
					if (this._DANHMUCMONAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDMMonAnChanging(value);
					this.SendPropertyChanging();
					this._MaDMMonAn = value;
					this.SendPropertyChanged("MaDMMonAn");
					this.OnMaDMMonAnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Anh", DbType="VarChar(150)")]
		public string Anh
		{
			get
			{
				return this._Anh;
			}
			set
			{
				if ((this._Anh != value))
				{
					this.OnAnhChanging(value);
					this.SendPropertyChanging();
					this._Anh = value;
					this.SendPropertyChanged("Anh");
					this.OnAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DanhGia", DbType="Int")]
		public System.Nullable<int> DanhGia
		{
			get
			{
				return this._DanhGia;
			}
			set
			{
				if ((this._DanhGia != value))
				{
					this.OnDanhGiaChanging(value);
					this.SendPropertyChanging();
					this._DanhGia = value;
					this.SendPropertyChanged("DanhGia");
					this.OnDanhGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaXoa", DbType="Bit")]
		public System.Nullable<bool> DaXoa
		{
			get
			{
				return this._DaXoa;
			}
			set
			{
				if ((this._DaXoa != value))
				{
					this.OnDaXoaChanging(value);
					this.SendPropertyChanging();
					this._DaXoa = value;
					this.SendPropertyChanged("DaXoa");
					this.OnDaXoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConMon", DbType="Bit")]
		public System.Nullable<bool> ConMon
		{
			get
			{
				return this._ConMon;
			}
			set
			{
				if ((this._ConMon != value))
				{
					this.OnConMonChanging(value);
					this.SendPropertyChanging();
					this._ConMon = value;
					this.SendPropertyChanged("ConMon");
					this.OnConMonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MONAN_CHITIETPHIEU", Storage="_CHITIETPHIEUs", ThisKey="MaMonAn", OtherKey="MaMonAn")]
		public EntitySet<CHITIETPHIEU> CHITIETPHIEUs
		{
			get
			{
				return this._CHITIETPHIEUs;
			}
			set
			{
				this._CHITIETPHIEUs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MONAN_BINHLUAN", Storage="_BINHLUANs", ThisKey="MaMonAn", OtherKey="MaMonAn")]
		public EntitySet<BINHLUAN> BINHLUANs
		{
			get
			{
				return this._BINHLUANs;
			}
			set
			{
				this._BINHLUANs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DANHMUCMONAN_MONAN", Storage="_DANHMUCMONAN", ThisKey="MaDMMonAn", OtherKey="MaDMMonAn", IsForeignKey=true)]
		public DANHMUCMONAN DANHMUCMONAN
		{
			get
			{
				return this._DANHMUCMONAN.Entity;
			}
			set
			{
				DANHMUCMONAN previousValue = this._DANHMUCMONAN.Entity;
				if (((previousValue != value) 
							|| (this._DANHMUCMONAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DANHMUCMONAN.Entity = null;
						previousValue.MONANs.Remove(this);
					}
					this._DANHMUCMONAN.Entity = value;
					if ((value != null))
					{
						value.MONANs.Add(this);
						this._MaDMMonAn = value.MaDMMonAn;
					}
					else
					{
						this._MaDMMonAn = default(Nullable<int>);
					}
					this.SendPropertyChanged("DANHMUCMONAN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHITIETPHIEUs(CHITIETPHIEU entity)
		{
			this.SendPropertyChanging();
			entity.MONAN = this;
		}
		
		private void detach_CHITIETPHIEUs(CHITIETPHIEU entity)
		{
			this.SendPropertyChanging();
			entity.MONAN = null;
		}
		
		private void attach_BINHLUANs(BINHLUAN entity)
		{
			this.SendPropertyChanging();
			entity.MONAN = this;
		}
		
		private void detach_BINHLUANs(BINHLUAN entity)
		{
			this.SendPropertyChanging();
			entity.MONAN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NGUOIDUNG")]
	public partial class NGUOIDUNG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TenDangNhap;
		
		private string _MatKhau;
		
		private string _Email;
		
		private string _DienThoai;
		
		private System.Nullable<bool> _DaXoa;
		
		private System.Nullable<int> _MaLoaiNguoiDung;
		
		private EntitySet<PHIEUDATCHO> _PHIEUDATCHOs;
		
		private EntityRef<LOAINGUOIDUNG> _LOAINGUOIDUNG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTenDangNhapChanging(string value);
    partial void OnTenDangNhapChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnDienThoaiChanging(string value);
    partial void OnDienThoaiChanged();
    partial void OnDaXoaChanging(System.Nullable<bool> value);
    partial void OnDaXoaChanged();
    partial void OnMaLoaiNguoiDungChanging(System.Nullable<int> value);
    partial void OnMaLoaiNguoiDungChanged();
    #endregion
		
		public NGUOIDUNG()
		{
			this._PHIEUDATCHOs = new EntitySet<PHIEUDATCHO>(new Action<PHIEUDATCHO>(this.attach_PHIEUDATCHOs), new Action<PHIEUDATCHO>(this.detach_PHIEUDATCHOs));
			this._LOAINGUOIDUNG = default(EntityRef<LOAINGUOIDUNG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDangNhap", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TenDangNhap
		{
			get
			{
				return this._TenDangNhap;
			}
			set
			{
				if ((this._TenDangNhap != value))
				{
					this.OnTenDangNhapChanging(value);
					this.SendPropertyChanging();
					this._TenDangNhap = value;
					this.SendPropertyChanged("TenDangNhap");
					this.OnTenDangNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienThoai", DbType="VarChar(50)")]
		public string DienThoai
		{
			get
			{
				return this._DienThoai;
			}
			set
			{
				if ((this._DienThoai != value))
				{
					this.OnDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._DienThoai = value;
					this.SendPropertyChanged("DienThoai");
					this.OnDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaXoa", DbType="Bit")]
		public System.Nullable<bool> DaXoa
		{
			get
			{
				return this._DaXoa;
			}
			set
			{
				if ((this._DaXoa != value))
				{
					this.OnDaXoaChanging(value);
					this.SendPropertyChanging();
					this._DaXoa = value;
					this.SendPropertyChanged("DaXoa");
					this.OnDaXoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiNguoiDung", DbType="Int")]
		public System.Nullable<int> MaLoaiNguoiDung
		{
			get
			{
				return this._MaLoaiNguoiDung;
			}
			set
			{
				if ((this._MaLoaiNguoiDung != value))
				{
					if (this._LOAINGUOIDUNG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLoaiNguoiDungChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiNguoiDung = value;
					this.SendPropertyChanged("MaLoaiNguoiDung");
					this.OnMaLoaiNguoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NGUOIDUNG_PHIEUDATCHO", Storage="_PHIEUDATCHOs", ThisKey="TenDangNhap", OtherKey="TenDangNhap")]
		public EntitySet<PHIEUDATCHO> PHIEUDATCHOs
		{
			get
			{
				return this._PHIEUDATCHOs;
			}
			set
			{
				this._PHIEUDATCHOs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAINGUOIDUNG_NGUOIDUNG", Storage="_LOAINGUOIDUNG", ThisKey="MaLoaiNguoiDung", OtherKey="MaLoaiNguoiDung", IsForeignKey=true)]
		public LOAINGUOIDUNG LOAINGUOIDUNG
		{
			get
			{
				return this._LOAINGUOIDUNG.Entity;
			}
			set
			{
				LOAINGUOIDUNG previousValue = this._LOAINGUOIDUNG.Entity;
				if (((previousValue != value) 
							|| (this._LOAINGUOIDUNG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOAINGUOIDUNG.Entity = null;
						previousValue.NGUOIDUNGs.Remove(this);
					}
					this._LOAINGUOIDUNG.Entity = value;
					if ((value != null))
					{
						value.NGUOIDUNGs.Add(this);
						this._MaLoaiNguoiDung = value.MaLoaiNguoiDung;
					}
					else
					{
						this._MaLoaiNguoiDung = default(Nullable<int>);
					}
					this.SendPropertyChanged("LOAINGUOIDUNG");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PHIEUDATCHOs(PHIEUDATCHO entity)
		{
			this.SendPropertyChanging();
			entity.NGUOIDUNG = this;
		}
		
		private void detach_PHIEUDATCHOs(PHIEUDATCHO entity)
		{
			this.SendPropertyChanging();
			entity.NGUOIDUNG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHIEUDATCHO")]
	public partial class PHIEUDATCHO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaPhieu;
		
		private System.Nullable<int> _MaBanAn;
		
		private string _TenDangNhap;
		
		private System.Nullable<System.DateTime> _NgayTaoPhieu;
		
		private System.Nullable<System.DateTime> _NgayDatBan;
		
		private System.Nullable<int> _MaTinhTrangPhieu;
		
		private System.Nullable<double> _TongTien;
		
		private EntitySet<CHITIETPHIEU> _CHITIETPHIEUs;
		
		private EntityRef<BANAN> _BANAN;
		
		private EntityRef<NGUOIDUNG> _NGUOIDUNG;
		
		private EntityRef<TINHTRANGPHIEU> _TINHTRANGPHIEU;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPhieuChanging(int value);
    partial void OnMaPhieuChanged();
    partial void OnMaBanAnChanging(System.Nullable<int> value);
    partial void OnMaBanAnChanged();
    partial void OnTenDangNhapChanging(string value);
    partial void OnTenDangNhapChanged();
    partial void OnNgayTaoPhieuChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayTaoPhieuChanged();
    partial void OnNgayDatBanChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayDatBanChanged();
    partial void OnMaTinhTrangPhieuChanging(System.Nullable<int> value);
    partial void OnMaTinhTrangPhieuChanged();
    partial void OnTongTienChanging(System.Nullable<double> value);
    partial void OnTongTienChanged();
    #endregion
		
		public PHIEUDATCHO()
		{
			this._CHITIETPHIEUs = new EntitySet<CHITIETPHIEU>(new Action<CHITIETPHIEU>(this.attach_CHITIETPHIEUs), new Action<CHITIETPHIEU>(this.detach_CHITIETPHIEUs));
			this._BANAN = default(EntityRef<BANAN>);
			this._NGUOIDUNG = default(EntityRef<NGUOIDUNG>);
			this._TINHTRANGPHIEU = default(EntityRef<TINHTRANGPHIEU>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhieu", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaPhieu
		{
			get
			{
				return this._MaPhieu;
			}
			set
			{
				if ((this._MaPhieu != value))
				{
					this.OnMaPhieuChanging(value);
					this.SendPropertyChanging();
					this._MaPhieu = value;
					this.SendPropertyChanged("MaPhieu");
					this.OnMaPhieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBanAn", DbType="Int")]
		public System.Nullable<int> MaBanAn
		{
			get
			{
				return this._MaBanAn;
			}
			set
			{
				if ((this._MaBanAn != value))
				{
					if (this._BANAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaBanAnChanging(value);
					this.SendPropertyChanging();
					this._MaBanAn = value;
					this.SendPropertyChanged("MaBanAn");
					this.OnMaBanAnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDangNhap", DbType="VarChar(50)")]
		public string TenDangNhap
		{
			get
			{
				return this._TenDangNhap;
			}
			set
			{
				if ((this._TenDangNhap != value))
				{
					if (this._NGUOIDUNG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTenDangNhapChanging(value);
					this.SendPropertyChanging();
					this._TenDangNhap = value;
					this.SendPropertyChanged("TenDangNhap");
					this.OnTenDangNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTaoPhieu", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayTaoPhieu
		{
			get
			{
				return this._NgayTaoPhieu;
			}
			set
			{
				if ((this._NgayTaoPhieu != value))
				{
					this.OnNgayTaoPhieuChanging(value);
					this.SendPropertyChanging();
					this._NgayTaoPhieu = value;
					this.SendPropertyChanged("NgayTaoPhieu");
					this.OnNgayTaoPhieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDatBan", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayDatBan
		{
			get
			{
				return this._NgayDatBan;
			}
			set
			{
				if ((this._NgayDatBan != value))
				{
					this.OnNgayDatBanChanging(value);
					this.SendPropertyChanging();
					this._NgayDatBan = value;
					this.SendPropertyChanged("NgayDatBan");
					this.OnNgayDatBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTinhTrangPhieu", DbType="Int")]
		public System.Nullable<int> MaTinhTrangPhieu
		{
			get
			{
				return this._MaTinhTrangPhieu;
			}
			set
			{
				if ((this._MaTinhTrangPhieu != value))
				{
					if (this._TINHTRANGPHIEU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTinhTrangPhieuChanging(value);
					this.SendPropertyChanging();
					this._MaTinhTrangPhieu = value;
					this.SendPropertyChanged("MaTinhTrangPhieu");
					this.OnMaTinhTrangPhieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongTien", DbType="Float")]
		public System.Nullable<double> TongTien
		{
			get
			{
				return this._TongTien;
			}
			set
			{
				if ((this._TongTien != value))
				{
					this.OnTongTienChanging(value);
					this.SendPropertyChanging();
					this._TongTien = value;
					this.SendPropertyChanged("TongTien");
					this.OnTongTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHIEUDATCHO_CHITIETPHIEU", Storage="_CHITIETPHIEUs", ThisKey="MaPhieu", OtherKey="MaPhieu")]
		public EntitySet<CHITIETPHIEU> CHITIETPHIEUs
		{
			get
			{
				return this._CHITIETPHIEUs;
			}
			set
			{
				this._CHITIETPHIEUs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BANAN_PHIEUDATCHO", Storage="_BANAN", ThisKey="MaBanAn", OtherKey="MaBan", IsForeignKey=true)]
		public BANAN BANAN
		{
			get
			{
				return this._BANAN.Entity;
			}
			set
			{
				BANAN previousValue = this._BANAN.Entity;
				if (((previousValue != value) 
							|| (this._BANAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BANAN.Entity = null;
						previousValue.PHIEUDATCHOs.Remove(this);
					}
					this._BANAN.Entity = value;
					if ((value != null))
					{
						value.PHIEUDATCHOs.Add(this);
						this._MaBanAn = value.MaBan;
					}
					else
					{
						this._MaBanAn = default(Nullable<int>);
					}
					this.SendPropertyChanged("BANAN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NGUOIDUNG_PHIEUDATCHO", Storage="_NGUOIDUNG", ThisKey="TenDangNhap", OtherKey="TenDangNhap", IsForeignKey=true)]
		public NGUOIDUNG NGUOIDUNG
		{
			get
			{
				return this._NGUOIDUNG.Entity;
			}
			set
			{
				NGUOIDUNG previousValue = this._NGUOIDUNG.Entity;
				if (((previousValue != value) 
							|| (this._NGUOIDUNG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NGUOIDUNG.Entity = null;
						previousValue.PHIEUDATCHOs.Remove(this);
					}
					this._NGUOIDUNG.Entity = value;
					if ((value != null))
					{
						value.PHIEUDATCHOs.Add(this);
						this._TenDangNhap = value.TenDangNhap;
					}
					else
					{
						this._TenDangNhap = default(string);
					}
					this.SendPropertyChanged("NGUOIDUNG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TINHTRANGPHIEU_PHIEUDATCHO", Storage="_TINHTRANGPHIEU", ThisKey="MaTinhTrangPhieu", OtherKey="MaTinhTrangPhieu", IsForeignKey=true)]
		public TINHTRANGPHIEU TINHTRANGPHIEU
		{
			get
			{
				return this._TINHTRANGPHIEU.Entity;
			}
			set
			{
				TINHTRANGPHIEU previousValue = this._TINHTRANGPHIEU.Entity;
				if (((previousValue != value) 
							|| (this._TINHTRANGPHIEU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TINHTRANGPHIEU.Entity = null;
						previousValue.PHIEUDATCHOs.Remove(this);
					}
					this._TINHTRANGPHIEU.Entity = value;
					if ((value != null))
					{
						value.PHIEUDATCHOs.Add(this);
						this._MaTinhTrangPhieu = value.MaTinhTrangPhieu;
					}
					else
					{
						this._MaTinhTrangPhieu = default(Nullable<int>);
					}
					this.SendPropertyChanged("TINHTRANGPHIEU");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHITIETPHIEUs(CHITIETPHIEU entity)
		{
			this.SendPropertyChanging();
			entity.PHIEUDATCHO = this;
		}
		
		private void detach_CHITIETPHIEUs(CHITIETPHIEU entity)
		{
			this.SendPropertyChanging();
			entity.PHIEUDATCHO = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BINHLUAN")]
	public partial class BINHLUAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaBinhLuan;
		
		private string _NoiDung;
		
		private System.Nullable<int> _DanhGia;
		
		private string _NguoiBinhLuan;
		
		private System.Nullable<System.DateTime> _ThoiGian;
		
		private System.Nullable<bool> _DaXoa;
		
		private System.Nullable<int> _MaMonAn;
		
		private EntityRef<MONAN> _MONAN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaBinhLuanChanging(int value);
    partial void OnMaBinhLuanChanged();
    partial void OnNoiDungChanging(string value);
    partial void OnNoiDungChanged();
    partial void OnDanhGiaChanging(System.Nullable<int> value);
    partial void OnDanhGiaChanged();
    partial void OnNguoiBinhLuanChanging(string value);
    partial void OnNguoiBinhLuanChanged();
    partial void OnThoiGianChanging(System.Nullable<System.DateTime> value);
    partial void OnThoiGianChanged();
    partial void OnDaXoaChanging(System.Nullable<bool> value);
    partial void OnDaXoaChanged();
    partial void OnMaMonAnChanging(System.Nullable<int> value);
    partial void OnMaMonAnChanged();
    #endregion
		
		public BINHLUAN()
		{
			this._MONAN = default(EntityRef<MONAN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBinhLuan", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaBinhLuan
		{
			get
			{
				return this._MaBinhLuan;
			}
			set
			{
				if ((this._MaBinhLuan != value))
				{
					this.OnMaBinhLuanChanging(value);
					this.SendPropertyChanging();
					this._MaBinhLuan = value;
					this.SendPropertyChanged("MaBinhLuan");
					this.OnMaBinhLuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung", DbType="NVarChar(400)")]
		public string NoiDung
		{
			get
			{
				return this._NoiDung;
			}
			set
			{
				if ((this._NoiDung != value))
				{
					this.OnNoiDungChanging(value);
					this.SendPropertyChanging();
					this._NoiDung = value;
					this.SendPropertyChanged("NoiDung");
					this.OnNoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DanhGia", DbType="Int")]
		public System.Nullable<int> DanhGia
		{
			get
			{
				return this._DanhGia;
			}
			set
			{
				if ((this._DanhGia != value))
				{
					this.OnDanhGiaChanging(value);
					this.SendPropertyChanging();
					this._DanhGia = value;
					this.SendPropertyChanged("DanhGia");
					this.OnDanhGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiBinhLuan", DbType="NVarChar(50)")]
		public string NguoiBinhLuan
		{
			get
			{
				return this._NguoiBinhLuan;
			}
			set
			{
				if ((this._NguoiBinhLuan != value))
				{
					this.OnNguoiBinhLuanChanging(value);
					this.SendPropertyChanging();
					this._NguoiBinhLuan = value;
					this.SendPropertyChanged("NguoiBinhLuan");
					this.OnNguoiBinhLuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGian", DbType="DateTime")]
		public System.Nullable<System.DateTime> ThoiGian
		{
			get
			{
				return this._ThoiGian;
			}
			set
			{
				if ((this._ThoiGian != value))
				{
					this.OnThoiGianChanging(value);
					this.SendPropertyChanging();
					this._ThoiGian = value;
					this.SendPropertyChanged("ThoiGian");
					this.OnThoiGianChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaXoa", DbType="Bit")]
		public System.Nullable<bool> DaXoa
		{
			get
			{
				return this._DaXoa;
			}
			set
			{
				if ((this._DaXoa != value))
				{
					this.OnDaXoaChanging(value);
					this.SendPropertyChanging();
					this._DaXoa = value;
					this.SendPropertyChanged("DaXoa");
					this.OnDaXoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMonAn", DbType="Int")]
		public System.Nullable<int> MaMonAn
		{
			get
			{
				return this._MaMonAn;
			}
			set
			{
				if ((this._MaMonAn != value))
				{
					if (this._MONAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaMonAnChanging(value);
					this.SendPropertyChanging();
					this._MaMonAn = value;
					this.SendPropertyChanged("MaMonAn");
					this.OnMaMonAnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MONAN_BINHLUAN", Storage="_MONAN", ThisKey="MaMonAn", OtherKey="MaMonAn", IsForeignKey=true)]
		public MONAN MONAN
		{
			get
			{
				return this._MONAN.Entity;
			}
			set
			{
				MONAN previousValue = this._MONAN.Entity;
				if (((previousValue != value) 
							|| (this._MONAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MONAN.Entity = null;
						previousValue.BINHLUANs.Remove(this);
					}
					this._MONAN.Entity = value;
					if ((value != null))
					{
						value.BINHLUANs.Add(this);
						this._MaMonAn = value.MaMonAn;
					}
					else
					{
						this._MaMonAn = default(Nullable<int>);
					}
					this.SendPropertyChanged("MONAN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
