<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="ChonTang.aspx.cs" Inherits="WARM.WebForm1" %>
<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">
<!--HTML SNIPPET GENERATED BY GIMP

WARNING!! This is NOT a fully valid HTML document, it is rather a piece of
HTML generated by GIMP's py-slice plugin that should be embedded in an HTML
or XHTML document to be valid.

Replace the href targets in the anchor (<a >) for your URLS to have it working
as a menu.
 -->
<table cellpadding="0" border="0" cellspacing="0">
  <tr><td><img alt=" " src="../images/ThamQuan/ChonTang/slice_0_0.jpg" style="width: 272px;  height: 200px; border-width: 0px;"/></td><td><img alt=" " src="../images/ThamQuan/ChonTang/slice_0_1.jpg" style="width: 356px;  height: 200px; border-width: 0px;"/></td><td><img alt=" " src="../images/ThamQuan/ChonTang/slice_0_2.jpg" style="width: 172px;  height: 200px; border-width: 0px;"/></td></tr>
  <tr><td><img alt=" " src="../images/ThamQuan/ChonTang/slice_1_0.jpg" style="width: 272px;  height: 80px; border-width: 0px;"/></td><td><a href="Tang2/Sanh1.aspx"><img onMouseOver="exchange(this,images_slice,explains,1);" onMouseOut="exchange(this,images_slice,explains,0);" alt="" src="../images/ThamQuan/ChonTang/slice_1_1.jpg" style="width: 356px; height: 80px; border-width: 0px" name="1_1" /></a></td><td><img alt=" " src="../images/ThamQuan/ChonTang/slice_1_2.jpg" style="width: 172px;  height: 80px; border-width: 0px;"/></td></tr>
  <tr><td><img alt=" " src="../images/ThamQuan/ChonTang/slice_2_0.jpg" style="width: 272px;  height: 38px; border-width: 0px;"/></td><td><img alt="" src="../images/ThamQuan/ChonTang/slice_2_1.jpg" style="width: 356px; height: 38px; border-width: 0px" name="2_1" /></td><td><img alt=" " src="../images/ThamQuan/ChonTang/slice_2_2.jpg" style="width: 172px;  height: 38px; border-width: 0px;"/></td></tr>
  <tr><td><img alt=" " src="../images/ThamQuan/ChonTang/slice_3_0.jpg" style="width: 272px;  height: 74px; border-width: 0px;"/></td><td><a href="Tang1/Sanh1.aspx"><img  onMouseOver="exchange(this,images_slice,explains,1);" onMouseOut="exchange(this,images_slice,explains,0);" alt="" src="../images/ThamQuan/ChonTang/slice_3_1.jpg" style="width: 356px; height: 74px; border-width: 0px" name="3_1" /></a></td><td><img alt=" " src="../images/ThamQuan/ChonTang/slice_3_2.jpg" style="width: 172px;  height: 74px; border-width: 0px;"/></td></tr>
  <tr><td><img alt=" " src="../images/ThamQuan/ChonTang/slice_4_0.jpg" style="width: 272px;  height: 36px; border-width: 0px;"/></td><td><img alt="" src="../images/ThamQuan/ChonTang/slice_4_1.jpg" style="width: 356px; height: 36px; border-width: 0px" name="4_1" /></td><td><img alt=" " src="../images/ThamQuan/ChonTang/slice_4_2.jpg" style="width: 172px;  height: 36px; border-width: 0px;"/></td></tr>
  <tr><td><img alt=" " src="../images/ThamQuan/ChonTang/slice_5_0.jpg" style="width: 272px;  height: 96px; border-width: 0px;"/></td><td><a href="TangTret/Sanh1.aspx"><img  onMouseOver="exchange(this,images_slice,explains,1);" onMouseOut="exchange(this,images_slice,explains,0);" alt="" src="../images/ThamQuan/ChonTang/slice_5_1.jpg" style="width: 356px; height: 96px; border-width: 0px" name="5_1" /></a></td><td><img alt=" " src="../images/ThamQuan/ChonTang/slice_5_2.jpg" style="width: 172px;  height: 96px; border-width: 0px;"/></td></tr>
  <tr><td><img alt=" " src="../images/ThamQuan/ChonTang/slice_6_0.jpg" style="width: 272px;  height: 76px; border-width: 0px;"/></td><td><img alt=" " src="../images/ThamQuan/ChonTang/slice_6_1.jpg" style="width: 356px;  height: 76px; border-width: 0px;"/></td><td><img alt=" " src="../images/ThamQuan/ChonTang/slice_6_2.jpg" style="width: 172px;  height: 76px; border-width: 0px;"/></td></tr>
</table>

<table cellpadding="0" border="0" cellspacing="0">
<tr>
    <td><a href="#"><img alt=" " src="../images/ThamQuan/ChonTang/struct.jpg" style="width: 150px;  height: 150px; border-width: 0px;" name="struct_image"></a></td>
    <td>
	<ul id="explain">
	</ul>
    </td>
</tr>
</table>


<script language="javascript" type="text/javascript">
    /* Made with GIMP */

    /* Preload images: */
    images_slice = new Array();

    images_slice["1_1_plain"] = new Image();
    images_slice["1_1_plain"].src = "../images/ThamQuan/ChonTang/slice_1_1.jpg";
    images_slice["3_1_plain"] = new Image();
    images_slice["3_1_plain"].src = "../images/ThamQuan/ChonTang/slice_3_1.jpg";
    images_slice["5_1_plain"] = new Image();
    images_slice["5_1_plain"].src = "../images/ThamQuan/ChonTang/slice_5_1.jpg";

    images_slice["1_1_hover"] = new Image();
    images_slice["1_1_hover"].src = "../images/ThamQuan/ChonTang/slice_1_1_hover.jpg";

    images_slice["3_1_hover"] = new Image();
    images_slice["3_1_hover"].src = "../images/ThamQuan/ChonTang/slice_3_1_hover.jpg";

    images_slice["5_1_hover"] = new Image();
    images_slice["5_1_hover"].src = "../images/ThamQuan/ChonTang/slice_5_1_hover.jpg";

    images_slice["1_1_struct"] = new Image();
    images_slice["1_1_struct"].src = "../images/ThamQuan/ChonTang/1_1_struct.jpg";
    images_slice["3_1_struct"] = new Image();
    images_slice["3_1_struct"].src = "../images/ThamQuan/ChonTang/3_1_struct.jpg";
    images_slice["5_1_struct"] = new Image();
    images_slice["5_1_struct"].src = "../images/ThamQuan/ChonTang/5_1_struct.jpg";

    explains = new Array();

    explains["1_1"] =
	"<li><a href=\"#\">1: Sanh 1</a></li>\
	<li><a href=\"#\">2: Sanh 2</a></li>\
	<li><a href=\"#\">3: Sanh 3</a></li>\
	<li><a href=\"#\">4: Sanh 4</a></li>";
    explains["3_1"] =
	"<li><a href=\"#\">1: Sanh 1</a></li>\
	<li><a href=\"#\">2: Sanh 2</a></li>\
	<li><a href=\"#\">3: Sanh 3</a></li>";
    explains["5_1"] =
	"<li><a href=\"#\">1: Sanh 1</a></li>\
	<li><a href=\"#\">2: Sanh 2</a></li>";
    explains["empty"] =
	"";

    function exchange(image, images_array_name, explains_array, event) {
        name = image.name;
        images = eval(images_array_name);
        explains = eval(explains_array);

        switch (event) {
            case 0:
                image.src = images[name + "_plain"].src;
                document.struct_image.src = "../images/ThamQuan/ChonTang/struct.jpg";
                document.getElementById("explain").innerHTML = explains["empty"];
                break;
            case 1:
                image.src = images[name + "_hover"].src;
                document.struct_image.src = images[name + "_struct"].src;
                document.getElementById("explain").innerHTML = explains[name];
                break;
            case 2:
                image.src = images[name + "_clicked"].src;
                break;
            case 3:
                image.src = images[name + "_hover"].src;
                break;
        }

    }
</script>
<!--
End of the part generated by GIMP
-->


</asp:Content>
